import 'package:flutter/foundation.dart';

import 'models.dart';
import 'sales_api.dart';

/// ChangeNotifier controller for sales screens (plans / wallet / subscriptions / keys).
class SalesState extends ChangeNotifier {
  SalesState(this.api);

  final SalesApi api;

  /// Tab indices for [SalesHomeScreen].
  static const tabPlans = 0;
  static const tabWallet = 1;
  static const tabSubscriptions = 2;
  static const tabKeys = 3;

  int? _requestedTab;

  /// Ask [SalesHomeScreen] to switch tabs (e.g. after purchase → subscriptions).
  void requestTab(int index) {
    _requestedTab = index;
    notifyListeners();
  }

  /// Consumed once by the entry screen listener.
  int? takeRequestedTab() {
    final t = _requestedTab;
    _requestedTab = null;
    return t;
  }


  List<Plan> plans = const [];
  Wallet? wallet;
  List<Subscription> subscriptions = const [];
  List<ApiKey> keys = const [];

  bool loadingPlans = false;
  bool loadingWallet = false;
  bool loadingSubscriptions = false;
  bool loadingKeys = false;
  bool purchasing = false;
  bool creatingKey = false;
  bool revokingKey = false;
  bool cancellingSubscription = false;
  bool renewingSubscription = false;
  int? lifecycleBusySubId;

  Object? plansError;
  Object? walletError;
  Object? subscriptionsError;
  Object? keysError;
  Object? purchaseError;
  Object? keyActionError;
  Object? subscriptionActionError;

  /// Idempotency key for the in-flight / last purchase attempt (reuse on retry).
  String? purchaseIdempotencyKey;
  int? purchasePlanId;

  /// Idempotency key for renew attempt (reuse on retry of same subscription).
  String? renewIdempotencyKey;
  int? renewSubscriptionId;

  bool get isLoggedIn => api.isLoggedIn;

  Future<void> loadPlans() async {
    loadingPlans = true;
    plansError = null;
    notifyListeners();
    try {
      plans = await api.getPlans();
    } catch (e) {
      plansError = e;
    } finally {
      loadingPlans = false;
      notifyListeners();
    }
  }

  Future<void> loadWallet() async {
    if (!isLoggedIn) return;
    loadingWallet = true;
    walletError = null;
    notifyListeners();
    try {
      wallet = await api.getWallet();
    } catch (e) {
      walletError = e;
    } finally {
      loadingWallet = false;
      notifyListeners();
    }
  }

  Future<void> loadSubscriptions() async {
    if (!isLoggedIn) return;
    loadingSubscriptions = true;
    subscriptionsError = null;
    notifyListeners();
    try {
      subscriptions = await api.getSubscriptions();
    } catch (e) {
      subscriptionsError = e;
    } finally {
      loadingSubscriptions = false;
      notifyListeners();
    }
  }

  Future<void> loadKeys() async {
    if (!isLoggedIn) return;
    loadingKeys = true;
    keysError = null;
    notifyListeners();
    try {
      keys = await api.getKeys();
    } catch (e) {
      keysError = e;
    } finally {
      loadingKeys = false;
      notifyListeners();
    }
  }

  Future<void> refreshAllAuthed() async {
    await Future.wait([loadWallet(), loadSubscriptions(), loadKeys()]);
  }

  /// Begin a new purchase attempt (new Idempotency-Key). Call before [purchase].
  void beginPurchaseAttempt(int planId) {
    purchasePlanId = planId;
    purchaseIdempotencyKey = SalesApi.newIdempotencyKey();
    purchaseError = null;
  }

  /// Purchase using the current attempt's Idempotency-Key (generated by [beginPurchaseAttempt]
  /// or reused when retrying the same attempt).
  Future<PurchaseResult?> purchase(int planId) async {
    if (!isLoggedIn) return null;
    if (purchasePlanId != planId || purchaseIdempotencyKey == null) {
      beginPurchaseAttempt(planId);
    }
    purchasing = true;
    purchaseError = null;
    notifyListeners();
    try {
      final result = await api.purchasePlan(planId, idempotencyKey: purchaseIdempotencyKey!);
      // Success: clear attempt key so a later purchase gets a fresh one.
      purchaseIdempotencyKey = null;
      purchasePlanId = null;
      // Refresh related state.
      wallet = Wallet(
        balance: result.balance,
        currency: wallet?.currency ?? 'IRT',
        unit: wallet?.unit ?? 'toman',
        ledger: wallet?.ledger ?? const [],
      );
      await Future.wait([loadWallet(), loadSubscriptions()]);
      return result;
    } catch (e) {
      purchaseError = e;
      // 409 idempotency_conflict: this key is bound to a different prior op —
      // mint a fresh key for the next tap. Keep the same key on 402/network/429
      // so a true retry of *this* attempt stays idempotent.
      if (e is SalesApiException && e.isIdempotencyConflict) {
        purchaseIdempotencyKey = SalesApi.newIdempotencyKey();
        purchasePlanId = planId;
      }
      return null;
    } finally {
      purchasing = false;
      notifyListeners();
    }
  }

  Future<CreateKeyResult?> createKey({String? name}) async {
    if (!isLoggedIn) return null;
    creatingKey = true;
    keyActionError = null;
    notifyListeners();
    try {
      final result = await api.createKey(name: name);
      await loadKeys();
      return result;
    } catch (e) {
      keyActionError = e;
      return null;
    } finally {
      creatingKey = false;
      notifyListeners();
    }
  }

  Future<bool> revokeKey(int id) async {
    if (!isLoggedIn) return false;
    revokingKey = true;
    keyActionError = null;
    notifyListeners();
    try {
      await api.revokeKey(id);
      await loadKeys();
      return true;
    } catch (e) {
      keyActionError = e;
      return false;
    } finally {
      revokingKey = false;
      notifyListeners();
    }
  }

  void beginRenewAttempt(int subscriptionId) {
    renewSubscriptionId = subscriptionId;
    renewIdempotencyKey = SalesApi.newIdempotencyKey();
    subscriptionActionError = null;
  }

  Future<CancelSubscriptionResult?> cancelSubscription(int id) async {
    if (!isLoggedIn) return null;
    cancellingSubscription = true;
    lifecycleBusySubId = id;
    subscriptionActionError = null;
    notifyListeners();
    try {
      final result = await api.cancelSubscription(id);
      await Future.wait([loadSubscriptions(), loadKeys()]);
      return result;
    } catch (e) {
      subscriptionActionError = e;
      return null;
    } finally {
      cancellingSubscription = false;
      lifecycleBusySubId = null;
      notifyListeners();
    }
  }

  Future<PurchaseResult?> renewSubscription(int id) async {
    if (!isLoggedIn) return null;
    if (renewSubscriptionId != id || renewIdempotencyKey == null) {
      beginRenewAttempt(id);
    }
    renewingSubscription = true;
    lifecycleBusySubId = id;
    subscriptionActionError = null;
    notifyListeners();
    try {
      final result = await api.renewSubscription(id, idempotencyKey: renewIdempotencyKey!);
      renewIdempotencyKey = null;
      renewSubscriptionId = null;
      wallet = Wallet(
        balance: result.balance,
        currency: wallet?.currency ?? 'IRT',
        unit: wallet?.unit ?? 'toman',
        ledger: wallet?.ledger ?? const [],
      );
      await Future.wait([loadWallet(), loadSubscriptions(), loadKeys()]);
      return result;
    } catch (e) {
      subscriptionActionError = e;
      if (e is SalesApiException && e.isIdempotencyConflict) {
        renewIdempotencyKey = SalesApi.newIdempotencyKey();
        renewSubscriptionId = id;
      }
      return null;
    } finally {
      renewingSubscription = false;
      lifecycleBusySubId = null;
      notifyListeners();
    }
  }
}
